### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/EmberRootZoo#1]
Minecraft: 1.12
Forge: 14.21.1.2443
EmberRoot Zoo: 1.0.0

[crash-2017-08-04_14.42.15-client.txt](https://github.com/PrinceOfAmber/EmberRootZoo/files/1200371/crash-2017-08-04_14.42.15-client.txt)

**Comment by Lothrazar** [comment]
Ah i see whats happening. ill get a fix out by tomorrow

**Comment by Lothrazar** [comment]
Fixed the crash the other day, sorry for the trouble https://minecraft.curseforge.com/projects/emberroot-zoo/files/2460835
