### ISSUE TITLE
Hostile mobs in peaceful. Also spawning WAY too often. default spawns way too high. (screenshot)

### ISSUE THREAD

**Issue by Lothrazar** [PrinceOfAmber/EmberRootZoo#10]
Default config file.

![2017-08-19_21 56 49](https://user-images.githubusercontent.com/621529/29492219-6aa6fdcc-8529-11e7-9c56-6284e95efc99.png)

**Comment by angelnc1989** [comment]
I just installed EmberRootZoo in my 1.12.1 instance and went in a test world.
I don't think that is supposed to happen:
![2017-09-18_15 08 02](https://user-images.githubusercontent.com/5382585/30543460-8ec0525a-9c83-11e7-91f5-1bb443c641fe.png)

**Comment by SDUBZ** [comment]
any chance of this getting figured out ? @PrinceOfAmber

**Comment by Lothrazar** [comment]
hey thanks for being patient im getting on to it this weekend.  I accidentally registered them as "passive" so just like bats they ignore spawn limits and all that.

**Comment by Lothrazar** [comment]
Fixed in latest release https://minecraft.curseforge.com/projects/emberroot-zoo/files/2488769
