### ISSUE TITLE
Sprouts spawning way too much

### ISSUE THREAD

**Issue by orionSquared** [PrinceOfAmber/EmberRootZoo#11]
Good evening,

I'm working on building my second pack and have been looking at adding this mod to my pack. I am working on it a bit, but
![2017-09-09_01 31 02](https://user-images.githubusercontent.com/17282982/30237403-723f8e6a-94ff-11e7-8451-59a2b5d4465d.png)
 so far, every work I create seems to become overrun with sprouts. The configs have them turned all the way down to the lowest possible without turning them off (a 1). And yet they're still super common. Any ideas on if I'm doing something wrong?

**Comment by orionSquared** [comment]
Ignore this. This isn't an issue with your mod at all. My apologies.

**Comment by Tokeli** [comment]
What's it an issue with, if not this mod? I've been struggling to figure out why so many of them are spawning, myself.

**Comment by orionSquared** [comment]
Honestly, I don't have the slightest clue yet. But it's not only happening to this mod. I have two mods that it's happening too. That's why I didnt want to say it was your mod causing the issue. 

I can't seem to find the issue so I'm having to rebuild the entire modpack from scratch, adding in mods one-by-one, hoping to find which one is causing the mobs to spawn so much.
