### ISSUE TITLE
Owls laying eggs way too frequently

### ISSUE THREAD

**Issue by angelnc1989** [PrinceOfAmber/EmberRootZoo#12]
I'm sitting on top of a Wild Owl and it poops out an egg every 1.5 seconds or so.
That might cause a lot of lag.

**Comment by Lothrazar** [comment]
Hey thanks for being patient, ill look into this soon

**Comment by Lothrazar** [comment]
Fixed in latest release https://minecraft.curseforge.com/projects/emberroot-zoo/files/2488769
